# 开发环境配置
server:
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    basedir: ./tmp
    # 最大等待数
    accept-count: 1000
    # 最大可被连接数
    max-connections: 10000
    # 最大工作线程数
    max-threads: 800
    # 最小工作线程数
    min-spare-threads: 100
  port: 8080

logging:
  level:
    com.greenbon: debug
  config: classpath:logback.xml

#spring系列配置
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 设置总上传的文件大小
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# mybatis-plus配置
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:com/greenbon/*/dao/*.xml,classpath:com/open/*/dao/*.xml
  typeAliasesPackage: com.greenbon.*.domain,com.open.*.domain
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    db-column-underline: true
    capital-mode: true